---
title: "Comparison vs FLASH"
author: "Youngseok Kim"
date: "2/13/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load code

```{r}
library(flashr); library(flashier); library(Rcpp); library(svd);
library(ebnm); library(ggplot2); library(cowplot)
sourceCpp('~/git/Youngseok/simplerflash/flashcaisa.cpp');
source('~/git/Youngseok/simplerflash/flash_caisa.R')
```

## Code for plotting

```{r}
plot_bar   <- function(factor, r, nncol = 5) {
  k         = ncol(factor)
  p         = nrow(factor)
  r         = 10
  df        = data.frame(x = 1:p, value = factor[,1], k = 1, group = as.factor(rep(1:r, each = p/r)))
  if (k > 1) {
    for (i in 2:k) {
      df    = rbind(df, data.frame(x = 1:p, value = factor[,i], k = i, group = as.factor(rep(1:r, each = p/r))))
    }
  }
  fig       = ggplot(df, aes_string(x = "x", y = "value", color = "group")) +
              geom_bar(stat = "identity") +# scale_color_manual(values = b[1:r]) +
              scale_x_discrete(labels = NULL) +
              theme_cowplot() +
              theme(axis.line       = element_blank(),
                    legend.position = "none") +
              facet_wrap(~k, ncol = nncol)
  fig
}
```

## Test 1

```{r}
# make data of size 1000 * 1000 with 20 non-gaussian factors
set.seed(1) # for reproducibility
ftrue = matrix(0,1000,20)
ltrue = matrix(0,1000,20)
for (i in 1:20) {
  ind = (1:50) + (i-1) * 50
  ltrue[ind,i] = rexp(50) * i^(1/2)
  ftrue[ind,i] = rexp(50)
}
Ytrue  = ltrue %*% t(ftrue)/5
Y      = Ytrue + rnorm(1000000)

system.time(out  <- flash_caisa(Y, 20, sa2 = pmax(2^(0:7) - 1, 0)^2,
                               maxiter = 1000, epstol = 1e-10, epoch = 2))[3]
system.time(out2 <- flash(Y, ebnm_fn = ebnm_ash, var_type = "constant",
                          ebnm_param = list(prior = "uniform", mixsd = pmax(2^(0:7) - 1, 0))))[3]
system.time(out3 <- flashier(Y, var.type = 0, prior.type = "normal.mixture",
                             ebnm.param = list(prior = "uniform", mixsd = pmax(2^(0:7) - 1, 0))))[3]
system.time(out4 <- flash_caisa(Y, ncol(out2$EF) - 1, sa2 = pmax(2^(0:7) - 1, 0)^2,
                                maxiter = 1000, epstol = 1e-10, epoch = 2))[3]

mean((Ytrue - out$A %*% t(out$B))^2)
mean((Ytrue - out2$EL %*% t(out2$EF))^2)
mean((Ytrue - out3$fit$EF[[1]] %*% t(out3$fit$EF[[2]]))^2)
mean((Ytrue - out4$A %*% t(out4$B))^2)
```

```{r}
pve       = colSums(out$A^2) * colSums(out$B^2)
pve_order = order(pve, decreasing = TRUE)
B         = out$B[,pve_order]
plot(pve[pve_order])
plot_bar(B, 20, 5)
```

```{r}
pve       = colSums(out3$fit$EF[[1]]^2) * colSums(out3$fit$EF[[2]]^2)
pve_order = order(pve, decreasing = TRUE)
B         = out3$fit$EF[[1]][,pve_order]
#B        = t(sqrt(colSums(out3$fit$EF[[2]]^2)) * t(out3$fit$EF[[1]]))[,pve_order]
plot(pve[pve_order])
plot_bar(B, 20, 5)
```

## Test 2

```{r}
set.seed(1) # for reproducibility
ftrue = matrix(0,2000,40)
ltrue = matrix(0,2000,40)
for (i in 1:40) {
  ind = (1:50) + (i-1) * 50
  ltrue[ind,i] = rexp(50) * i^(1/2)
  ftrue[ind,i] = rexp(50)
}
Ytrue  = ltrue %*% t(ftrue)/10
Y      = Ytrue + rnorm(4000000)

system.time(out  <- flash_caisa(Y, 40, sa2 = pmax(2^(0:7) - 1, 0)^2,
                               maxiter = 1000, epstol = 1e-10, epoch = 2))[3]
system.time(out3 <- flashier(Y, var.type = 0, prior.type = "normal.mixture",
                             ebnm.param = list(prior = "uniform", mixsd = pmax(2^(0:7) - 1, 0))))[3]

mean((Ytrue - out$A %*% t(out$B))^2)
#mean((Ytrue - out2$EL %*% t(out2$EF))^2)
mean((Ytrue - out3$fit$EF[[1]] %*% t(out3$fit$EF[[2]]))^2)
```

```{r}
pve       = colSums(out$A^2) * colSums(out$B^2)
pve_order = order(pve, decreasing = TRUE)
B         = out$B[,pve_order]
plot(pve[pve_order])
plot_bar(B, 40, 5)
```

```{r}
pve       = colSums(out3$fit$EF[[1]]^2) * colSums(out3$fit$EF[[2]]^2)
pve_order = order(pve, decreasing = TRUE)
B         = out3$fit$EF[[1]][,pve_order]
#B        = t(sqrt(colSums(out3$fit$EF[[2]]^2)) * t(out3$fit$EF[[1]]))[,pve_order]
plot(pve[pve_order])
plot_bar(B, 40, 5)
```

## Test 3

```{r}
# make data of size 1000 * 1000 with 20 non-gaussian factors
set.seed(1) # for reproducibility
ftrue = matrix(0,1000,50)
ltrue = matrix(0,1000,50)
for (i in 1:50) {
  ind = (1:20) + (i-1) * 20
  ltrue[ind,i] = rexp(20) * i^(1/3)
  ftrue[ind,i] = rexp(20)
}
Ytrue  = ltrue %*% t(ftrue)
Y      = Ytrue + rnorm(1000000)

system.time(out  <- flash_caisa(Y, 50, sa2 = pmax(2^(0:7) - 1, 0)^2, convtol = 1e-6,
                               maxiter = 1000, epstol = 1e-10, epoch = 2))[3]
system.time(out2 <- flash(Y, ebnm_fn = ebnm_ash, var_type = "constant",
                          ebnm_param = list(prior = "uniform", mixsd = pmax(2^(0:7) - 1, 0))))[3]
system.time(out3 <- flashier(Y, var.type = 0, prior.type = "normal.mixture",
                             ebnm.param = list(prior = "uniform", mixsd = pmax(2^(0:7) - 1, 0))))[3]
system.time(out4 <- flash_caisa(Y, ncol(out2$EF), sa2 = pmax(2^(0:7) - 1, 0)^2, convtol = 1e-8,
                                maxiter = 1000, epstol = 1e-10, epoch = 2))[3]

mean((Ytrue - out$A %*% t(out$B))^2)
mean((Ytrue - out2$EL %*% t(out2$EF))^2)
mean((Ytrue - out3$fit$EF[[1]] %*% t(out3$fit$EF[[2]]))^2)
mean((Ytrue - out4$A %*% t(out4$B))^2)
```

```{r}
pve       = colSums(out$A^2) * colSums(out$B^2)
pve_order = order(pve, decreasing = TRUE)
B         = out$B[,pve_order]
plot(pve[pve_order])
plot_bar(B, 100, 5)
```

```{r}
pve       = colSums(out3$fit$EF[[1]]^2) * colSums(out3$fit$EF[[2]]^2)
pve_order = order(pve, decreasing = TRUE)
B         = out3$fit$EF[[1]][,pve_order]
#B        = t(sqrt(colSums(out3$fit$EF[[2]]^2)) * t(out3$fit$EF[[1]]))[,pve_order]
plot(pve[pve_order])
plot_bar(B, 100, 5)
```